### ISSUE TITLE
自动标签对TR无效

### ISSUE THREAD

**Issue by junyuyuan** [hotlcc/MoviePilot-Plugins-Third#10]
日志如下，勾选TR的自动标签选项，保存，然后再打开立即执行一次，再保存后的执行日志，没有TR替换标签日志。

```
【INFO】2024-07-11 20:42:44,921 - downloaderhelper - 插件配置加载完成：{'listen_download_event': True, 'listen_source_file_event': True, 'cron': '0/30 * * * *', 'exclude_tags': 'BT,刷流', 'dashboard_widget_refresh': 5, 'dashboard_speed_widget_refresh': 5, 'site_name_priority': True, 'tag_prefix': '站点/', 'dashboard_widget_size': 12, 'dashboard_widget_target_downloaders': ['qbittorrent', 'transmission'], 'dashboard_widget_display_fields': ['NAME', 'SELECT_SIZE', 'COMPLETED', 'STATE', 'DOWNLOAD_SPEED', 'UPLOAD_SPEED', 'REMAINING_TIME', 'RATIO', 'TAGS', 'ADD_TIME', 'UPLOADED'], 'dashboard_speed_widget_target_downloaders': ['qbittorrent', 'transmission'], '_tabs': 'transmission', 'undefined': True, 'enable': True, '_config_tracker_mappings_dialog_closed': False, 'qb_enable': True, 'qb_enable_tagging': True, 'qb_enable_seeding': True, 'qb_enable_delete': True, 'run_once': False, 'tr_enable_delete': True, 'tr_enable': True, '_config_dashboard_active_torrent_dialog_closed': False, 'enable_dashboard_widget': True, '_config_dashboard_speed_dialog_closed': False, 'enable_dashboard_speed_widget': True, 'tr_enable_seeding': True, 'tr_enable_tagging': True}
【INFO】2024-07-11 20:42:44,918 - downloaderhelper - 插件服务停止完成
【INFO】2024-07-11 20:42:44,917 - downloaderhelper - 插件未启用缓存，无须清除
【INFO】2024-07-11 20:42:44,916 - downloaderhelper - 尝试清除插件缓存...
【INFO】2024-07-11 20:42:44,914 - downloaderhelper - 插件未启用服务调度器，无须停止
【INFO】2024-07-11 20:42:44,913 - downloaderhelper - 尝试停止插件服务调度器...
【INFO】2024-07-11 20:42:44,912 - downloaderhelper - 尝试停止插件服务...
【INFO】2024-07-11 20:42:36,320 - downloaderhelper - 插件配置加载完成：{'listen_download_event': True, 'listen_source_file_event': True, 'cron': '0/30 * * * *', 'exclude_tags': 'BT,刷流', 'dashboard_widget_refresh': 5, 'dashboard_speed_widget_refresh': 5, 'site_name_priority': True, 'tag_prefix': '站点/', 'dashboard_widget_size': 12, 'dashboard_widget_target_downloaders': ['qbittorrent', 'transmission'], 'dashboard_widget_display_fields': ['NAME', 'SELECT_SIZE', 'COMPLETED', 'STATE', 'DOWNLOAD_SPEED', 'UPLOAD_SPEED', 'REMAINING_TIME', 'RATIO', 'TAGS', 'ADD_TIME', 'UPLOADED'], 'dashboard_speed_widget_target_downloaders': ['qbittorrent', 'transmission'], '_tabs': 'transmission', 'undefined': True, 'enable': True, '_config_tracker_mappings_dialog_closed': False, 'qb_enable': True, 'qb_enable_tagging': True, 'qb_enable_seeding': True, 'qb_enable_delete': True, 'run_once': False, 'tr_enable_delete': True, 'tr_enable': True, '_config_dashboard_active_torrent_dialog_closed': False, 'enable_dashboard_widget': True, '_config_dashboard_speed_dialog_closed': False, 'enable_dashboard_speed_widget': True, 'tr_enable_seeding': True, 'tr_enable_tagging': True}
【INFO】2024-07-11 20:42:36,315 - downloaderhelper - 插件服务停止完成
【INFO】2024-07-11 20:42:36,314 - downloaderhelper - 插件未启用缓存，无须清除
【INFO】2024-07-11 20:42:36,312 - downloaderhelper - 尝试清除插件缓存...
【INFO】2024-07-11 20:42:36,311 - downloaderhelper - 插件未启用服务调度器，无须停止
【INFO】2024-07-11 20:42:36,309 - downloaderhelper - 尝试停止插件服务调度器...
【INFO】2024-07-11 20:42:36,308 - downloaderhelper - 尝试停止插件服务...
【INFO】2024-07-11 20:41:26,696 - downloaderhelper - 插件配置加载完成：{'listen_download_event': True, 'listen_source_file_event': True, 'cron': '0/30 * * * *', 'exclude_tags': 'BT,刷流', 'dashboard_widget_refresh': 5, 'dashboard_speed_widget_refresh': 5, 'site_name_priority': True, 'tag_prefix': '站点/', 'dashboard_widget_size': 12, 'dashboard_widget_target_downloaders': ['qbittorrent', 'transmission'], 'dashboard_widget_display_fields': ['NAME', 'SELECT_SIZE', 'COMPLETED', 'STATE', 'DOWNLOAD_SPEED', 'UPLOAD_SPEED', 'REMAINING_TIME', 'RATIO', 'TAGS', 'ADD_TIME', 'UPLOADED'], 'dashboard_speed_widget_target_downloaders': ['qbittorrent', 'transmission'], '_tabs': 'qbittorrent', 'undefined': True, 'enable': True, '_config_tracker_mappings_dialog_closed': False, 'qb_enable': True, 'qb_enable_tagging': True, 'qb_enable_seeding': True, 'qb_enable_delete': True, 'run_once': False, 'tr_enable_delete': True, 'tr_enable': True, '_config_dashboard_active_torrent_dialog_closed': False, 'enable_dashboard_widget': True, '_config_dashboard_speed_dialog_closed': False, 'enable_dashboard_speed_widget': True, 'tr_enable_seeding': True}
【INFO】2024-07-11 20:41:26,692 - downloaderhelper - 插件服务停止完成
【INFO】2024-07-11 20:41:26,690 - downloaderhelper - 插件未启用缓存，无须清除
【INFO】2024-07-11 20:41:26,687 - downloaderhelper - 尝试清除插件缓存...
【INFO】2024-07-11 20:41:26,685 - downloaderhelper - 插件服务调度器停止成功
【INFO】2024-07-11 20:41:26,683 - downloaderhelper - 尝试停止插件服务调度器...
【INFO】2024-07-11 20:41:26,680 - downloaderhelper - 尝试停止插件服务...
【INFO】2024-07-11 20:30:02,494 - downloaderhelper - 下载器[qBittorrent]任务执行成功
【INFO】2024-07-11 20:30:02,492 - downloaderhelper - [QB]批量自动删种结束
【INFO】2024-07-11 20:30:02,487 - downloaderhelper - [QB]批量自动删种开始...
【INFO】2024-07-11 20:30:02,485 - downloaderhelper - [QB]批量自动做种结束
【INFO】2024-07-11 20:30:02,474 - downloaderhelper - [QB]批量自动做种开始...
【INFO】2024-07-11 20:30:02,472 - downloaderhelper - [QB]批量自动标签结束
【INFO】2024-07-11 20:30:02,397 - downloaderhelper - [QB]单个自动标签成功: hash = 809a5695db725a37a11d4667dcae7df9fad77504, name = 疯狂动物城.Zootopia.2016.CHN.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS, size = 5.59G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:02,335 - downloaderhelper - [QB]单个自动标签成功: hash = b36c992c69c9aecb99ab1a7f8dc2f2605ca8fd0c, name = V.for.Vendetta.2005.UHD.BluRay.2160p.10bit.HDR.2Audio.TrueHD(Atmos).7.1.x265-beAst, size = 29.34G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:02,278 - downloaderhelper - [QB]单个自动标签成功: hash = 0d9f36ec11fd6ed45298bb5a1beed638eeca5e26, name = Lotus Lantern 1999 WEB-DL 2160P H265 AAC-Dave.mp4, size = 1.37G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:02,197 - downloaderhelper - [QB]单个自动标签成功: hash = 67f7db89e52593ec4df5d2d930cc14712448cf41, name = 猫鼠游戏.Catch.Me.If.You.Can.2002.BluRay.1080p.x265.10bit.2Audio.MNHD-FRDS, size = 9.22G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:02,125 - downloaderhelper - [QB]单个自动标签成功: hash = 3168eb2ffbec9ff39683e7ba9e0c569d223deca5, name = 武林外传.My.Own.Swordsman.S01.2006.1080p.WEB-DL.H264.AAC-HHWEB, size = 45.91G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:02,041 - downloaderhelper - [QB]单个自动标签成功: hash = 938c8aca2ce6e3cb1b48c93d2c8909527d5fb423, name = 华尔街之狼.The.Wolf.of.Wall.Street.2013.BluRay.1080p.x265.10bit.MNHD-FRDS, size = 8.61G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:01,726 - downloaderhelper - [QB]单个自动标签成功: hash = 6e6b94c0c23cbd10635b920825016ca4b449a69c, name = [那年那兔那些事儿 番外篇].Year.Hare.Affair.2016.S00.Complete.2160p.WEB-DL.AVC.AAC-QHstudIo, size = 3.22G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:01,561 - downloaderhelper - [QB]单个自动标签成功: hash = fd63a86568993487bc0702ea0978287dbac6f044, name = 黑社会, size = 596.8M, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
【INFO】2024-07-11 20:30:01,525 - downloaderhelper - [QB]单个自动标签成功: hash = 7c85c5c0e70e7d47438d257ee5f865df60ee6da9, name = Taxi 1998 GER BluRay Remux 1080p AVC DTS-HD MA 5.1-OurBits, size = 24.21G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
```

**Comment by hotlcc** [comment]
> 日志如下，勾选TR的自动标签选项，保存，然后再打开立即执行一次，再保存后的执行日志，没有TR替换标签日志。
> 
> ```
> 【INFO】2024-07-11 20:42:44,921 - downloaderhelper - 插件配置加载完成：{'listen_download_event': True, 'listen_source_file_event': True, 'cron': '0/30 * * * *', 'exclude_tags': 'BT,刷流', 'dashboard_widget_refresh': 5, 'dashboard_speed_widget_refresh': 5, 'site_name_priority': True, 'tag_prefix': '站点/', 'dashboard_widget_size': 12, 'dashboard_widget_target_downloaders': ['qbittorrent', 'transmission'], 'dashboard_widget_display_fields': ['NAME', 'SELECT_SIZE', 'COMPLETED', 'STATE', 'DOWNLOAD_SPEED', 'UPLOAD_SPEED', 'REMAINING_TIME', 'RATIO', 'TAGS', 'ADD_TIME', 'UPLOADED'], 'dashboard_speed_widget_target_downloaders': ['qbittorrent', 'transmission'], '_tabs': 'transmission', 'undefined': True, 'enable': True, '_config_tracker_mappings_dialog_closed': False, 'qb_enable': True, 'qb_enable_tagging': True, 'qb_enable_seeding': True, 'qb_enable_delete': True, 'run_once': False, 'tr_enable_delete': True, 'tr_enable': True, '_config_dashboard_active_torrent_dialog_closed': False, 'enable_dashboard_widget': True, '_config_dashboard_speed_dialog_closed': False, 'enable_dashboard_speed_widget': True, 'tr_enable_seeding': True, 'tr_enable_tagging': True}
> 【INFO】2024-07-11 20:42:44,918 - downloaderhelper - 插件服务停止完成
> 【INFO】2024-07-11 20:42:44,917 - downloaderhelper - 插件未启用缓存，无须清除
> 【INFO】2024-07-11 20:42:44,916 - downloaderhelper - 尝试清除插件缓存...
> 【INFO】2024-07-11 20:42:44,914 - downloaderhelper - 插件未启用服务调度器，无须停止
> 【INFO】2024-07-11 20:42:44,913 - downloaderhelper - 尝试停止插件服务调度器...
> 【INFO】2024-07-11 20:42:44,912 - downloaderhelper - 尝试停止插件服务...
> 【INFO】2024-07-11 20:42:36,320 - downloaderhelper - 插件配置加载完成：{'listen_download_event': True, 'listen_source_file_event': True, 'cron': '0/30 * * * *', 'exclude_tags': 'BT,刷流', 'dashboard_widget_refresh': 5, 'dashboard_speed_widget_refresh': 5, 'site_name_priority': True, 'tag_prefix': '站点/', 'dashboard_widget_size': 12, 'dashboard_widget_target_downloaders': ['qbittorrent', 'transmission'], 'dashboard_widget_display_fields': ['NAME', 'SELECT_SIZE', 'COMPLETED', 'STATE', 'DOWNLOAD_SPEED', 'UPLOAD_SPEED', 'REMAINING_TIME', 'RATIO', 'TAGS', 'ADD_TIME', 'UPLOADED'], 'dashboard_speed_widget_target_downloaders': ['qbittorrent', 'transmission'], '_tabs': 'transmission', 'undefined': True, 'enable': True, '_config_tracker_mappings_dialog_closed': False, 'qb_enable': True, 'qb_enable_tagging': True, 'qb_enable_seeding': True, 'qb_enable_delete': True, 'run_once': False, 'tr_enable_delete': True, 'tr_enable': True, '_config_dashboard_active_torrent_dialog_closed': False, 'enable_dashboard_widget': True, '_config_dashboard_speed_dialog_closed': False, 'enable_dashboard_speed_widget': True, 'tr_enable_seeding': True, 'tr_enable_tagging': True}
> 【INFO】2024-07-11 20:42:36,315 - downloaderhelper - 插件服务停止完成
> 【INFO】2024-07-11 20:42:36,314 - downloaderhelper - 插件未启用缓存，无须清除
> 【INFO】2024-07-11 20:42:36,312 - downloaderhelper - 尝试清除插件缓存...
> 【INFO】2024-07-11 20:42:36,311 - downloaderhelper - 插件未启用服务调度器，无须停止
> 【INFO】2024-07-11 20:42:36,309 - downloaderhelper - 尝试停止插件服务调度器...
> 【INFO】2024-07-11 20:42:36,308 - downloaderhelper - 尝试停止插件服务...
> 【INFO】2024-07-11 20:41:26,696 - downloaderhelper - 插件配置加载完成：{'listen_download_event': True, 'listen_source_file_event': True, 'cron': '0/30 * * * *', 'exclude_tags': 'BT,刷流', 'dashboard_widget_refresh': 5, 'dashboard_speed_widget_refresh': 5, 'site_name_priority': True, 'tag_prefix': '站点/', 'dashboard_widget_size': 12, 'dashboard_widget_target_downloaders': ['qbittorrent', 'transmission'], 'dashboard_widget_display_fields': ['NAME', 'SELECT_SIZE', 'COMPLETED', 'STATE', 'DOWNLOAD_SPEED', 'UPLOAD_SPEED', 'REMAINING_TIME', 'RATIO', 'TAGS', 'ADD_TIME', 'UPLOADED'], 'dashboard_speed_widget_target_downloaders': ['qbittorrent', 'transmission'], '_tabs': 'qbittorrent', 'undefined': True, 'enable': True, '_config_tracker_mappings_dialog_closed': False, 'qb_enable': True, 'qb_enable_tagging': True, 'qb_enable_seeding': True, 'qb_enable_delete': True, 'run_once': False, 'tr_enable_delete': True, 'tr_enable': True, '_config_dashboard_active_torrent_dialog_closed': False, 'enable_dashboard_widget': True, '_config_dashboard_speed_dialog_closed': False, 'enable_dashboard_speed_widget': True, 'tr_enable_seeding': True}
> 【INFO】2024-07-11 20:41:26,692 - downloaderhelper - 插件服务停止完成
> 【INFO】2024-07-11 20:41:26,690 - downloaderhelper - 插件未启用缓存，无须清除
> 【INFO】2024-07-11 20:41:26,687 - downloaderhelper - 尝试清除插件缓存...
> 【INFO】2024-07-11 20:41:26,685 - downloaderhelper - 插件服务调度器停止成功
> 【INFO】2024-07-11 20:41:26,683 - downloaderhelper - 尝试停止插件服务调度器...
> 【INFO】2024-07-11 20:41:26,680 - downloaderhelper - 尝试停止插件服务...
> 【INFO】2024-07-11 20:30:02,494 - downloaderhelper - 下载器[qBittorrent]任务执行成功
> 【INFO】2024-07-11 20:30:02,492 - downloaderhelper - [QB]批量自动删种结束
> 【INFO】2024-07-11 20:30:02,487 - downloaderhelper - [QB]批量自动删种开始...
> 【INFO】2024-07-11 20:30:02,485 - downloaderhelper - [QB]批量自动做种结束
> 【INFO】2024-07-11 20:30:02,474 - downloaderhelper - [QB]批量自动做种开始...
> 【INFO】2024-07-11 20:30:02,472 - downloaderhelper - [QB]批量自动标签结束
> 【INFO】2024-07-11 20:30:02,397 - downloaderhelper - [QB]单个自动标签成功: hash = 809a5695db725a37a11d4667dcae7df9fad77504, name = 疯狂动物城.Zootopia.2016.CHN.BluRay.1080p.x265.10bit.4Audio.MNHD-FRDS, size = 5.59G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:02,335 - downloaderhelper - [QB]单个自动标签成功: hash = b36c992c69c9aecb99ab1a7f8dc2f2605ca8fd0c, name = V.for.Vendetta.2005.UHD.BluRay.2160p.10bit.HDR.2Audio.TrueHD(Atmos).7.1.x265-beAst, size = 29.34G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:02,278 - downloaderhelper - [QB]单个自动标签成功: hash = 0d9f36ec11fd6ed45298bb5a1beed638eeca5e26, name = Lotus Lantern 1999 WEB-DL 2160P H265 AAC-Dave.mp4, size = 1.37G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:02,197 - downloaderhelper - [QB]单个自动标签成功: hash = 67f7db89e52593ec4df5d2d930cc14712448cf41, name = 猫鼠游戏.Catch.Me.If.You.Can.2002.BluRay.1080p.x265.10bit.2Audio.MNHD-FRDS, size = 9.22G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:02,125 - downloaderhelper - [QB]单个自动标签成功: hash = 3168eb2ffbec9ff39683e7ba9e0c569d223deca5, name = 武林外传.My.Own.Swordsman.S01.2006.1080p.WEB-DL.H264.AAC-HHWEB, size = 45.91G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:02,041 - downloaderhelper - [QB]单个自动标签成功: hash = 938c8aca2ce6e3cb1b48c93d2c8909527d5fb423, name = 华尔街之狼.The.Wolf.of.Wall.Street.2013.BluRay.1080p.x265.10bit.MNHD-FRDS, size = 8.61G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:01,726 - downloaderhelper - [QB]单个自动标签成功: hash = 6e6b94c0c23cbd10635b920825016ca4b449a69c, name = [那年那兔那些事儿 番外篇].Year.Hare.Affair.2016.S00.Complete.2160p.WEB-DL.AVC.AAC-QHstudIo, size = 3.22G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:01,561 - downloaderhelper - [QB]单个自动标签成功: hash = fd63a86568993487bc0702ea0978287dbac6f044, name = 黑社会, size = 596.8M, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> 【INFO】2024-07-11 20:30:01,525 - downloaderhelper - [QB]单个自动标签成功: hash = 7c85c5c0e70e7d47438d257ee5f865df60ee6da9, name = Taxi 1998 GER BluRay Remux 1080p AVC DTS-HD MA 5.1-OurBits, size = 24.21G, before = 已整理, 蟹黄堡, 辅种, after = 已整理, 辅种, PT, 站点/蟹黄堡
> ```

你贴的日志最后那几行不是吗？？
