### ISSUE TITLE
标签重复

### ISSUE THREAD

**Issue by glfdxh** [hotlcc/MoviePilot-Plugins-Third#12]
<img width="1510" alt="截屏2024-07-19 15 46 27" src="https://github.com/user-attachments/assets/36495946-9712-410e-ab91-8dbceea37254">
报告老师，该站点tracker里有两条，然后看到他会被标上两个站点，请问是否有修复的可能

**Comment by hotlcc** [comment]
> <img alt="截屏2024-07-19 15 46 27" width="1510" src="https://private-user-images.githubusercontent.com/157491224/350536837-36495946-9712-410e-ab91-8dbceea37254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDE4NjIsIm5iZiI6MTcyMTQ0MTU2MiwicGF0aCI6Ii8xNTc0OTEyMjQvMzUwNTM2ODM3LTM2NDk1OTQ2LTk3MTItNDEwZS1hYjkxLThkYmNlZWEzNzI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwMjEyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmFkMzQ1N2IwYjViYjg1YzY1MTRlZGY2NzdiYTBlYjE5NjY3MjJiNWU0ZTliZWIwYzQxMDEzMWYzOTdjNjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q2_gbh0yiJOGzUrjq7IAJ-oaymRv2U60Gvyu5vA9USM"> 报告老师，该站点tracker里有两条，然后看到他会被标上两个站点，请问是否有修复的可能

通过配置【Tracker映射】把hdkylin这个域名映射为站点域名。

**Comment by hotlcc** [comment]
<img width="726" alt="image" src="https://github.com/user-attachments/assets/6c5cd327-a8c2-4b79-8351-3caf568786a6">

**Comment by glfdxh** [comment]
<img width="311" alt="截屏2024-07-20 10 16 16" src="https://github.com/user-attachments/assets/4f31013f-e561-40b6-8322-083d8557b436"><img width="662" alt="截屏2024-07-20 10 16 50" src="https://github.com/user-attachments/assets/60428e26-4091-4f9f-a2ee-2f9f93940905">
大佬，我根据你的提示添加了映射之后，它站点反而变多了，无论是映射其中一个tracker还是映射两个都不能让该站点的标签变为一个
