### ISSUE TITLE
PT/BT标签去掉，或者增加开关

### ISSUE THREAD

**Issue by samyang211** [hotlcc/MoviePilot-Plugins-Third#20]
建议去掉自动PT/BT标签，或增加开关选项。
个人都是PT站点，所有种子都有这个标签，感觉对我来说意义就不大了，还有一些多余

感谢作者。

**Comment by hotlcc** [comment]
> 建议去掉自动PT/BT标签，或增加开关选项。 个人都是PT站点，所有种子都有这个标签，感觉对我来说意义就不大了，还有一些多余
> 
> 感谢作者。

PT标签和站点标签是联动的，判断有PT标签才会加站点标签。另外你只有PT资源不代表所有人都是，就两个字母能有啥多余。而且添加额外的开关会导致配置界面杂乱，我需要的是精简配置，即插即用。
