### ISSUE TITLE
下载器助手执行异常

### ISSUE THREAD

**Issue by dyimo** [hotlcc/MoviePilot-Plugins-Third#21]
KeyError: 'tr'
         ~~~~~^^^^^^
    tr = query['tr']
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1231, in __parse_tracker_for_qbittorrent
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    tracker_url = self.__parse_tracker_for_qbittorrent(torrent=torrent)
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1917, in __tagging_single_for_qbittorrent
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    if self.__tagging_single_for_qbittorrent(qbittorrent=qbittorrent, torrent=torrent):
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1883, in __tagging_batch_for_qbittorrent
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result.set_tagging(self.__tagging_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents))
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1794, in __run_for_qbittorrent
Traceback (most recent call last):

**Comment by hotlcc** [comment]
> KeyError: 'tr' ~~~~~^^^^^^ tr = query['tr'] File "/app/app/plugins/downloaderhelper/**init**.py", line 1231, in __parse_tracker_for_qbittorrent ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tracker_url = self.__parse_tracker_for_qbittorrent(torrent=torrent) File "/app/app/plugins/downloaderhelper/**init**.py", line 1917, in __tagging_single_for_qbittorrent ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ if self.__tagging_single_for_qbittorrent(qbittorrent=qbittorrent, torrent=torrent): File "/app/app/plugins/downloaderhelper/**init**.py", line 1883, in __tagging_batch_for_qbittorrent ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ result.set_tagging(self.__tagging_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents)) File "/app/app/plugins/downloaderhelper/**init**.py", line 1794, in __run_for_qbittorrent Traceback (most recent call last):

提供一下种子
