### ISSUE TITLE
插件优化

### ISSUE THREAD

**Issue by hotlcc** [hotlcc/MoviePilot-Plugins-Third#25]
- [x] 【聚合消息通知】注释修正：
   <img width="634" alt="image" src="https://github.com/user-attachments/assets/1b6d0f7c-d8b8-41e1-8f98-166a31aa3cff">
- [ ] ~~【下载器助手】配置界面优化~~
- [ ] 【下载器助手】支持自动加速排队等待
   当状态为`queuedUP` （排队等候）的种子数量或百分比达到一定阈值时，调整配置“Torrent 非活动计时器”（`slow_torrent_inactive_timer`）的值为1秒，种子排队结束后或低于一定阈值时还原该配置值。

**Comment by shyblacktea** [comment]
老板 再优化下吧 用的[OneBot-11] 
媒体库服务器通知插件开启了 新入库消息 emby没那个库 plex有(但设定-媒体服务器-plex未同步这个库)
这库有新片会在QQ发送这个入库消息(emby没设置这库所以没问题)❎
vx和tg 无此库入库消息 ☑️

**Comment by madrays** [comment]
大佬这是什么原因呢
【INFO】2024-11-01 23:00:10,679 - downloaderhelper - 尝试停止插件服务...
【ERROR】2024-11-01 22:57:06,512 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:56:56,465 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:56:46,414 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:56:36,353 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:56:26,289 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:56:16,224 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:56:05,970 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【ERROR】2024-11-01 22:55:57,362 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
【INFO】2024-11-01 22:55:56,048 - downloaderhelper - 下载添加事件监听任务执行结束
【INFO】2024-11-01 22:55:56,042 - downloaderhelper - 下载添加事件监听任务执行开始...

**Comment by hotlcc** [comment]
> 大佬这是什么原因呢 【INFO】2024-11-01 23:00:10,679 - downloaderhelper - 尝试停止插件服务... 【ERROR】2024-11-01 22:57:06,512 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:56:56,465 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:56:46,414 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:56:36,353 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:56:26,289 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:56:16,224 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:56:05,970 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【ERROR】2024-11-01 22:55:57,362 - qbittorrent.py - 获取种子列表出错：unhashable type: 'list' 【INFO】2024-11-01 22:55:56,048 - downloaderhelper - 下载添加事件监听任务执行结束 【INFO】2024-11-01 22:55:56,042 - downloaderhelper - 下载添加事件监听任务执行开始...

这个问题别人提过，但是我没复现出来

**Comment by madrays** [comment]
需要提供什么配置吗佬

**Comment by hotlcc** [comment]
> 需要提供什么配置吗佬

qb版本
