### ISSUE TITLE
自动删除种子会多次执行、多次通知

### ISSUE THREAD

**Issue by MillerArice** [hotlcc/MoviePilot-Plugins-Third#26]
我在mp中设置“清理硬连接”插件监测到某硬连接被删除时，自动清理其源文件和其种子文件，自动删种动作由“下载器助手”完成，并配置TG通知，每次删除硬连接后“清理硬连接”通知只有不重复的一条通知，而“下载器助手”会不同情况的多次通知，查看日志发现是因为执行了多次删除命令，如下图，试过重置插件、卸载插件、用“插件彻底卸载”插件去卸载插件都没能解决。
<img width="1489" alt="截屏2024-08-26 下午5 25 57" src="https://github.com/user-attachments/assets/eeab2525-6a29-4ae1-ae75-47d087270c0b">
<img width="377" alt="截屏2024-08-26 下午5 26 13" src="https://github.com/user-attachments/assets/f829365e-d5fd-482c-a574-53ed9d7500f6">

**Comment by hotlcc** [comment]
> 我在mp中设置“清理硬连接”插件监测到某硬连接被删除时，自动清理其源文件和其种子文件，自动删种动作由“下载器助手”完成，并配置TG通知，每次删除硬连接后“清理硬连接”通知只有不重复的一条通知，而“下载器助手”会不同情况的多次通知，查看日志发现是因为执行了多次删除命令，如下图，试过重置插件、卸载插件、用“插件彻底卸载”插件去卸载插件都没能解决。 <img alt="截屏2024-08-26 下午5 25 57" width="1489" src="https://private-user-images.githubusercontent.com/54389951/361385851-eeab2525-6a29-4ae1-ae75-47d087270c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU4NTEtZWVhYjI1MjUtNmEyOS00YWUxLWFlNzUtNDdkMDg3MjcwYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1OTVmMmE4ZTBlNDhkYmNkMDZhMDdlNmNjODE0ODIxMzgzNDE2N2E1YmUwYjNiZWIzZTFiNzgzZTVjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8ufvMRBv1q4McpULdI1QWz2zG63VzyVxPKqIf-hDcY"> <img alt="截屏2024-08-26 下午5 26 13" width="377" src="https://private-user-images.githubusercontent.com/54389951/361385901-f829365e-d5fd-482c-a574-53ed9d7500f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU5MDEtZjgyOTM2NWUtZDVmZC00ODJjLWE1NzQtNTNlZDlkNzUwMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTIzM2Y1MGI3YjhkMTdmNDQxYmIyMWFlYjQ3NzAzOGQ5ZjIxN2NkZjM5OGRkNzUzZTEwOTRkOTA1OThhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Na9bmpU7w6LnK5Qzy2XpNVOkFEEi_3p78GBv3pOWf28">

是不是升级最新版后才出现的问题？是不是以前没有这个问题？

**Comment by MillerArice** [comment]
> > 我在mp中设置“清理硬连接”插件监测到某硬连接被删除时，自动清理其源文件及其文件，自动删除种子动作由“下载器助手”完成，并配置TG通知，每次删除硬连接后“清理硬连接”通知只有不重复的一条通知，而“下载器助手”会不同情况的多次通知，查看日志命令发现是因为执行了多次删除，如下图，尝试重置插件、卸载插件、用“插件彻底卸载”插件去卸载插件未能解决。<img alt="截屏2024-08-26 下午5 25 57" width="1489" src="https://private-user-images.githubusercontent.com/54389951/361385851-eeab2525-6a29-4ae1-ae75-47d087270c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU4NTEtZWVhYjI1MjUtNmEyOS00YWUxLWFlNzUtNDdkMDg3MjcwYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1OTVmMmE4ZTBlNDhkYmNkMDZhMDdlNmNjODE0ODIxMzgzNDE2N2E1YmUwYjNiZWIzZTFiNzgzZTVjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8ufvMRBv1q4McpULdI1QWz2zG63VzyVxPKqIf-hDcY"> <img alt="截屏2024-08-26 下午5 26 13" width="377" src="https://private-user-images.githubusercontent.com/54389951/361385901-f829365e-d5fd-482c-a574-53ed9d7500f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU5MDEtZjgyOTM2NWUtZDVmZC00ODJjLWE1NzQtNTNlZDlkNzUwMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTIzM2Y1MGI3YjhkMTdmNDQxYmIyMWFlYjQ3NzAzOGQ5ZjIxN2NkZjM5OGRkNzUzZTEwOTRkOTA1OThhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Na9bmpU7w6LnK5Qzy2XpNVOkFEEi_3p78GBv3pOWf28">
> 
> 是不是升级最新版本后才出现的问题？是不是以前没有这个问题？

我不太确定，因为我没有注意版本号，我能安装到旧版本的插件吗？

**Comment by hotlcc** [comment]
> > > 我在mp中设置“清理硬连接”插件监测到某硬连接被删除时，自动清理其源文件及其文件，自动删除种子动作由“下载器助手”完成，并配置TG通知，每次删除硬连接后“清理硬连接”通知只有不重复的一条通知，而“下载器助手”会不同情况的多次通知，查看日志命令发现是因为执行了多次删除，如下图，尝试重置插件、卸载插件、用“插件彻底卸载”插件去卸载插件未能解决。<img alt="截屏2024-08-26 下午5 25 57" width="1489" src="https://private-user-images.githubusercontent.com/54389951/361385851-eeab2525-6a29-4ae1-ae75-47d087270c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU4NTEtZWVhYjI1MjUtNmEyOS00YWUxLWFlNzUtNDdkMDg3MjcwYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1OTVmMmE4ZTBlNDhkYmNkMDZhMDdlNmNjODE0ODIxMzgzNDE2N2E1YmUwYjNiZWIzZTFiNzgzZTVjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8ufvMRBv1q4McpULdI1QWz2zG63VzyVxPKqIf-hDcY"> <img alt="截屏2024-08-26 下午5 26 13" width="377" src="https://private-user-images.githubusercontent.com/54389951/361385901-f829365e-d5fd-482c-a574-53ed9d7500f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU5MDEtZjgyOTM2NWUtZDVmZC00ODJjLWE1NzQtNTNlZDlkNzUwMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTIzM2Y1MGI3YjhkMTdmNDQxYmIyMWFlYjQ3NzAzOGQ5ZjIxN2NkZjM5OGRkNzUzZTEwOTRkOTA1OThhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Na9bmpU7w6LnK5Qzy2XpNVOkFEEi_3p78GBv3pOWf28">
> > 
> > 
> > 是不是升级最新版本后才出现的问题？是不是以前没有这个问题？
> 
> 我不太确定，因为我没有注意版本号，我能安装到旧版本的插件吗？

你看一下版本号啊。另外刚刚更新了v3.5.2，关注一下该版本是否还有问题。

**Comment by MillerArice** [comment]
> > > > 我在mp中设置“清理硬连接”插件监测到某硬连接被删除时，自动清理其源文件及其文件，自动删除种子动作由“下载器助手”完成，并配置TG通知，每次删除硬连接后“清理硬连接”通知只有不重复的一条通知，而“下载器助手”会不同情况的多次通知，查看日志命令发现是因为执行了多次删除，如下图，尝试重置插件、卸载插件、用“插件彻底卸载”插件去卸载插件未能解决。<img alt="截屏2024-08-26 下午5 25 57" width="1489" src="https://private-user-images.githubusercontent.com/54389951/361385851-eeab2525-6a29-4ae1-ae75-47d087270c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU4NTEtZWVhYjI1MjUtNmEyOS00YWUxLWFlNzUtNDdkMDg3MjcwYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1OTVmMmE4ZTBlNDhkYmNkMDZhMDdlNmNjODE0ODIxMzgzNDE2N2E1YmUwYjNiZWIzZTFiNzgzZTVjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8ufvMRBv1q4McpULdI1QWz2zG63VzyVxPKqIf-hDcY"> <img alt="截屏2024-08-26 下午5 26 13" width="377" src="https://private-user-images.githubusercontent.com/54389951/361385901-f829365e-d5fd-482c-a574-53ed9d7500f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU5MDEtZjgyOTM2NWUtZDVmZC00ODJjLWE1NzQtNTNlZDlkNzUwMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTIzM2Y1MGI3YjhkMTdmNDQxYmIyMWFlYjQ3NzAzOGQ5ZjIxN2NkZjM5OGRkNzUzZTEwOTRkOTA1OThhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Na9bmpU7w6LnK5Qzy2XpNVOkFEEi_3p78GBv3pOWf28">
> > > 
> > > 
> > > 是不是升级最新版本后才出现的问题？是不是以前没有这个问题？
> > 
> > 
> > 我不太确定，因为我没有注意版本号，我能安装到旧版本的插件吗？
> 
> 你看一下版本号啊。另外刚刚更新了v3.5.2，关注一下该版本是否还有问题。

我目前还是3.5.1版本，等我更新后再观察观察，稍后回复问题是否消失。

**Comment by MillerArice** [comment]
> > > > 我在mp中设置“清理硬连接”插件监测到某硬连接被删除时，自动清理其源文件及其文件，自动删除种子动作由“下载器助手”完成，并配置TG通知，每次删除硬连接后“清理硬连接”通知只有不重复的一条通知，而“下载器助手”会不同情况的多次通知，查看日志命令发现是因为执行了多次删除，如下图，尝试重置插件、卸载插件、用“插件彻底卸载”插件去卸载插件未能解决。<img alt="截屏2024-08-26 下午5 25 57" width="1489" src="https://private-user-images.githubusercontent.com/54389951/361385851-eeab2525-6a29-4ae1-ae75-47d087270c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU4NTEtZWVhYjI1MjUtNmEyOS00YWUxLWFlNzUtNDdkMDg3MjcwYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTk1OTVmMmE4ZTBlNDhkYmNkMDZhMDdlNmNjODE0ODIxMzgzNDE2N2E1YmUwYjNiZWIzZTFiNzgzZTVjNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8ufvMRBv1q4McpULdI1QWz2zG63VzyVxPKqIf-hDcY"> <img alt="截屏2024-08-26 下午5 26 13" width="377" src="https://private-user-images.githubusercontent.com/54389951/361385901-f829365e-d5fd-482c-a574-53ed9d7500f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjcxNTAsIm5iZiI6MTcyNDcyNjg1MCwicGF0aCI6Ii81NDM4OTk1MS8zNjEzODU5MDEtZjgyOTM2NWUtZDVmZC00ODJjLWE1NzQtNTNlZDlkNzUwMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwNTIzM2Y1MGI3YjhkMTdmNDQxYmIyMWFlYjQ3NzAzOGQ5ZjIxN2NkZjM5OGRkNzUzZTEwOTRkOTA1OThhYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Na9bmpU7w6LnK5Qzy2XpNVOkFEEi_3p78GBv3pOWf28">
> > > 
> > > 
> > > 是不是升级最新版本后才出现的问题？是不是以前没有这个问题？
> > 
> > 
> > 我不太确定，因为我没有注意版本号，我能安装到旧版本的插件吗？
> 
> 你看一下版本号啊。另外刚刚更新了v3.5.2，关注一下该版本是否还有问题。

更新至v3.5.2版本后测试问题得到解决，没有出现多次通知的情况，感谢回复🙏
