### ISSUE TITLE
下载器助手3.5.3修复3.5.2的自动删种错误，在mp更新到1.9.15后又重新出现了。

### ISSUE THREAD

**Issue by buzidjy** [hotlcc/MoviePilot-Plugins-Third#28]
TypeError: TorrentInfoList.__init__() missing 1 required positional argument: 'client'
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.__class__(self.data[i])
  File "/usr/local/lib/python3.11/collections/__init__.py", line 1239, in __getitem__
                    ~~~~~~~~^^^
    torrents_copy = torrents[:]
  File "/app/app/plugins/downloaderhelper/__init__.py", line 2023, in __delete_batch_for_qbittorrent
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents,
  File "/app/app/plugins/downloaderhelper/__init__.py", line 1804, in __run_for_qbittorrent
Traceback (most recent call last):
【ERROR】2024-08-28 16:56:50,791 - downloaderhelper - 下载器[qBittorrent]任务执行失败: TorrentInfoList.__init__() missing 1 required positional argument: 'client'

![image](https://github.com/user-attachments/assets/45cb0ca0-6ec7-49bf-bcec-64ec9c36eda7)
![image](https://github.com/user-attachments/assets/7b822428-afa7-4d21-ad0c-06c595000b07)
![image](https://github.com/user-attachments/assets/ccf84a97-c247-4aef-aaed-9cf1db9526e5)

**Comment by hotlcc** [comment]
> TypeError: TorrentInfoList.**init**() missing 1 required positional argument: 'client' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ return self.**class**(self.data[i]) File "/usr/local/lib/python3.11/collections/**init**.py", line 1239, in **getitem** ~~~~~~~~^^^ torrents_copy = torrents[:] File "/app/app/plugins/downloaderhelper/**init**.py", line 2023, in __delete_batch_for_qbittorrent ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents, File "/app/app/plugins/downloaderhelper/**init**.py", line 1804, in __run_for_qbittorrent Traceback (most recent call last): 【ERROR】2024-08-28 16:56:50,791 - downloaderhelper - 下载器[qBittorrent]任务执行失败: TorrentInfoList.**init**() missing 1 required positional argument: 'client'
> 
> ![image](https://private-user-images.githubusercontent.com/122658705/362213986-45cb0ca0-6ec7-49bf-bcec-64ec9c36eda7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDk4OTAsIm5iZiI6MTcyNDg0OTU5MCwicGF0aCI6Ii8xMjI2NTg3MDUvMzYyMjEzOTg2LTQ1Y2IwY2EwLTZlYzctNDliZi1iY2VjLTY0ZWM5YzM2ZWRhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMjUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDhmNjFlMGUxMmM3NjI3ZTZmOTM4Yjc2N2QxZTdiNWQ2YTRlYzUyNjJjMTkxOWYxMGU4YjEwOWJjNDI1Y2E5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WZpb1cgtJpeAEA_gW1zcxwen2BAkGVCSd-vqdbvEWE8) ![image](https://private-user-images.githubusercontent.com/122658705/362214233-7b822428-afa7-4d21-ad0c-06c595000b07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDk4OTAsIm5iZiI6MTcyNDg0OTU5MCwicGF0aCI6Ii8xMjI2NTg3MDUvMzYyMjE0MjMzLTdiODIyNDI4LWFmYTctNGQyMS1hZDBjLTA2YzU5NTAwMGIwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMjUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDhmOTRmZDJmOGZjNDg3MWQwNTJlNDNhNjkxNjg2ZGE3NzdhN2U1ZGQ2NzViYzA4MTkxNGExYThiZTRjZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pYZ-GaK9rQ4Qgkt6hd-jAUDl4GugtLzK_iEjO--3vRE) ![image](https://private-user-images.githubusercontent.com/122658705/362214330-ccf84a97-c247-4aef-aaed-9cf1db9526e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDk4OTAsIm5iZiI6MTcyNDg0OTU5MCwicGF0aCI6Ii8xMjI2NTg3MDUvMzYyMjE0MzMwLWNjZjg0YTk3LWMyNDctNGFlZi1hYWVkLTljZjFkYjk1MjZlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMjUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGYzNzZiZTI1YjUyOTIzNjc3ZWUwNTE1MDM4ZjY3YzIwOGM5N2E2MGQ3MTU2M2VmNjUwMGRiNzkxNDgyOTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5NfqLL1xLC6ON59FT3DKTCf1AZtLiXbGRdp_xGcozXY)

检查一下是不是添加了别的包含本插件且版本低于本插件的插件仓库导致？我的没有问题，相关问题代码先前就改了的：
<img width="469" alt="image" src="https://github.com/user-attachments/assets/ef5335bb-9fac-4fe9-a3a6-892c203dc28b">

**Comment by hotlcc** [comment]
我好像知道问题了

**Comment by hotlcc** [comment]
升级3.5.4
