### ISSUE TITLE
关于聚合消息通知

### ISSUE THREAD

**Issue by Putarku** [hotlcc/MoviePilot-Plugins-Third#29]
我使用http请求的方式推送消息给qq机器人，但受限于[gocqhttp](https://docs.go-cqhttp.org/api/#%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF)api的限制，单次post只能发送一条信息并且只能写入一个群号，例如我想要同时发送给多个群就没有办法了。能否增加循环调用的配置？

**Comment by hotlcc** [comment]
受限于mp插件ui组件的局限性，无法实现多item实例的功能。因此一次send行为只能向目标发起一次请求，如果目标api不支持群发则无法实现你的需求。后续可能会考虑推出面向有一定技术功底的用户使用的纯yml配置的高级版插件实现更加灵活的配置。

**Comment by hotlcc** [comment]
另外，也可以添加一个专用渠道支持你的需求，不过你需要提供一下api文档

**Comment by Putarku** [comment]
[gocqhttp的API文档](https://docs.go-cqhttp.org/api/)，一般只要关注私聊信息和群聊信息这两条即可。

**Comment by Putarku** [comment]
目前使用插件往`{"group_id": "788634xxx","message": "[CQ:image,file=${image}]\n${title}"}`

**Comment by hotlcc** [comment]
> [gocqhttp的API文档](https://docs.go-cqhttp.org/api/)，一般只要关注私聊信息和群聊信息这两条即可。 [onebot-11的API文档](https://github.com/botuniverse/onebot-11/blob/master/communication/http.md)，是规范的标准，和上面的是一样的API调用方法，描述更详细一些。

意思使go-cqhttp使onebot11规范的一个实现吗

**Comment by Putarku** [comment]
> > [gocqhttp的API文档](https://docs.go-cqhttp.org/api/)，一般只要关注私聊信息和群聊信息这两条即可。 [onebot-11的API文档](https://github.com/botuniverse/onebot-11/blob/master/communication/http.md)，是规范的标准，和上面的是一样的API调用方法，描述更详细一些。
> 
> 意思是go-cqhttp是onebot11规范的一个实现吗

是的

**Comment by hotlcc** [comment]
> [CQ:image,file=${image}]

更新v1.2，顺便帮测试一下吧，我这边没有环境，测完在这里反馈一下

**Comment by Putarku** [comment]
测试了下发送消息都没什么问题了，不过这个消息的拼接感觉可以优化一下，而且换行好像多了一点。
现在是这样的
![QQ_1726671263559](https://github.com/user-attachments/assets/f06249e8-e3a6-495b-a993-bbccf51190c2)
之前拼接出来的这样感觉效果会好一些
![QQ_1726671289255](https://github.com/user-attachments/assets/3fc6949c-1821-4ff4-8a6b-f0bc7b966b8a)

**Comment by hotlcc** [comment]
> [CQ:image,file=${image}]\n${title}\n${text}

升级1.3看一下，我这边懒得搭环境了
