### ISSUE TITLE
新版聚合消息通知，OneBOT默认消息模板，无图片的消息发不了

### ISSUE THREAD

**Issue by DaiDai-X** [hotlcc/MoviePilot-Plugins-Third#30]
默认的消息模板，带图片，使得没有图片的消息（例如站点消息数据统计等），发送不出来
能不能吧兼容下，谢谢

**Comment by hotlcc** [comment]
> 默认的消息模板，带图片，使得没有图片的消息（例如站点消息数据统计等），发送不出来 能不能吧兼容下，谢谢

已支持Mako模板引擎语法
