### ISSUE TITLE
希望可以兼容模板格式

### ISSUE THREAD

**Issue by 4Nest** [hotlcc/MoviePilot-Plugins-Third#31]
希望大佬可以兼容这种格式的模板
{% if year %} ({{year}}){% endif %}
因为如果text为空的时候，发送的时候显示None，感觉不是很好看。
![image](https://github.com/user-attachments/assets/ec6ae23a-1fe9-43ce-aa9b-7fdc81e3725d)

**Comment by hotlcc** [comment]
> 希望大佬可以兼容这种格式的模板 {% if year %} ({{year}}){% endif %} 因为如果text为空的时候，发送的时候显示None，感觉不是很好看。 ![image](https://private-user-images.githubusercontent.com/74977868/369238222-ec6ae23a-1fe9-43ce-aa9b-7fdc81e3725d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NDc4MjcsIm5iZiI6MTcyNjg0NzUyNywicGF0aCI6Ii83NDk3Nzg2OC8zNjkyMzgyMjItZWM2YWUyM2EtMWZlOS00M2NlLWFhOWItN2ZkYzgxZTM3MjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDE1NTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOGZmZDdjNDc4ZmIyZTIxMDFiMGExMDhkMjIzZGU3YzBjZjFiNGE4OWNjZjU3NGUwZTc5Y2M1MDIwYjg1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2wdVntT6K6qv5e0XpRlBtRsQ1Al-MsghhMtADno5M20)

已支持Mako模板引擎语法
