### ISSUE TITLE
聚合站点开关，需要支持自定义站点

### ISSUE THREAD

**Issue by android-zhaoyongtao** [hotlcc/MoviePilot-Plugins-Third#32]
站点签到、登录，站点数据统计都是支持自定义站点的。您这个插件里不显示，所以保存后会将前面已经添加的自定义站点给去掉。站点举例海豹
PS:MP 站点管理里也不显示自定义站点，但自定义站点其实已经通过 cookie 同步过去账号等信息了，所以签到、统计 都正常。

**Comment by hotlcc** [comment]
ok，确实没有考虑这块，后续研究一下。自定义站点是指通过那个插件添加的吗？

**Comment by hotlcc** [comment]
我没用过自定义站点，你提供一下配置吧（去除掉敏感信息）

**Comment by hotlcc** [comment]
另外，确定一下是哪个插件添加的
<img width="760" alt="image" src="https://github.com/user-attachments/assets/0d6a7332-fb2f-4e03-884f-5e0b75c6b66f">
