### ISSUE TITLE
下载器助手V2版活动种子仪表盘组件报错

### ISSUE THREAD

**Issue by XuJingDaoZhang** [hotlcc/MoviePilot-Plugins-Third#35]
![QQ20241023-210350](https://github.com/user-attachments/assets/234861a7-9bda-4953-8c58-b3a7f43237c1)
配置好仪表板活动种子的设置后启动组件开关 , 然后在MP的仪表板勾选启用组件,下载器助手报如上错误

**Comment by yellowstrong** [comment]
并且V2任务执行没有办法发送TG通知，但是系统通知有

**Comment by hotlcc** [comment]
> ![QQ20241023-210350](https://private-user-images.githubusercontent.com/16450753/379279570-234861a7-9bda-4953-8c58-b3a7f43237c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjQ2ODYsIm5iZiI6MTcyOTgyNDM4NiwicGF0aCI6Ii8xNjQ1MDc1My8zNzkyNzk1NzAtMjM0ODYxYTctOWJkYS00OTUzLThjNTgtYjNhN2Y0MzIzN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAyNDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3Yzg3YzRmNzIwMWM0N2U1NGJmOWVlYmE4YjUyZmU5ZjM0ZGY4YTM5ZTBjYWQ4ZGJjNGMyNGQzMjkwMzM5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLu7Ja5XAFsGJfthKs59MRYIxmzd5sHwsxfZYpY-B7k) 配置好仪表板活动种子的设置后启动组件开关 , 然后在MP的仪表板勾选启用组件,下载器助手报如上错误

没复现你的问题，我这边qb-4.6.4一切正常。麻烦提供qb版本和能定位到行的日志

**Comment by hotlcc** [comment]
> 并且V2任务执行没有办法发送TG通知，但是系统通知有

TG需要选择支持【插件】消息类型

**Comment by yellowstrong** [comment]
> > ![QQ20241023-210350](https://private-user-images.githubusercontent.com/16450753/379279570-234861a7-9bda-4953-8c58-b3a7f43237c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjQ2ODYsIm5iZiI6MTcyOTgyNDM4NiwicGF0aCI6Ii8xNjQ1MDc1My8zNzkyNzk1NzAtMjM0ODYxYTctOWJkYS00OTUzLThjNTgtYjNhN2Y0MzIzN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAyNDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3Yzg3YzRmNzIwMWM0N2U1NGJmOWVlYmE4YjUyZmU5ZjM0ZGY4YTM5ZTBjYWQ4ZGJjNGMyNGQzMjkwMzM5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLu7Ja5XAFsGJfthKs59MRYIxmzd5sHwsxfZYpY-B7k) 配置好仪表板活动种子的设置后启动组件开关 , 然后在MP的仪表板勾选启用组件,下载器助手报如上错误
> 
> 没复现你的问题，我这边qb-4.6.4一切正常。麻烦提供qb版本和能定位到行的日志

qb是5.0版本

ERROR:   qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
INFO:     10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK
INFO:     10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
ERROR:   qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
INFO:     10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK
INFO:     10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
ERROR:   qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
INFO:     10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK
INFO:     10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
INFO:     10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK
ERROR:   qbittorrent.py - 获取种子列表出错：unhashable type: 'list'
INFO:     10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK

**Comment by hotlcc** [comment]
> > > ![QQ20241023-210350](https://private-user-images.githubusercontent.com/16450753/379279570-234861a7-9bda-4953-8c58-b3a7f43237c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MjQ2ODYsIm5iZiI6MTcyOTgyNDM4NiwicGF0aCI6Ii8xNjQ1MDc1My8zNzkyNzk1NzAtMjM0ODYxYTctOWJkYS00OTUzLThjNTgtYjNhN2Y0MzIzN2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAyNDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3Yzg3YzRmNzIwMWM0N2U1NGJmOWVlYmE4YjUyZmU5ZjM0ZGY4YTM5ZTBjYWQ4ZGJjNGMyNGQzMjkwMzM5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bLu7Ja5XAFsGJfthKs59MRYIxmzd5sHwsxfZYpY-B7k) 配置好仪表板活动种子的设置后启动组件开关 , 然后在MP的仪表板勾选启用组件,下载器助手报如上错误
> > 
> > 
> > 没复现你的问题，我这边qb-4.6.4一切正常。麻烦提供qb版本和能定位到行的日志
> 
> qb是5.0版本
> 
> ERROR: qbittorrent.py - 获取种子列表出错：unhashable type: 'list' INFO: 10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK INFO: 10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK ERROR: qbittorrent.py - 获取种子列表出错：unhashable type: 'list' INFO: 10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK INFO: 10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK ERROR: qbittorrent.py - 获取种子列表出错：unhashable type: 'list' INFO: 10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK INFO: 10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK INFO: 10.0.0.2:0 - "GET /api/v1/dashboard/downloader HTTP/1.1" 200 OK ERROR: qbittorrent.py - 获取种子列表出错：unhashable type: 'list' INFO: 10.0.0.2:0 - "GET /api/v1/plugin/dashboard/DownloaderHelper/active_torrent_QB HTTP/1.1" 200 OK

5.0版本也没有发现你的问题，提供一下活动种子仪表板的字段配置（如果不是默认的话）

**Comment by yellowstrong** [comment]
![image](https://github.com/user-attachments/assets/c044db87-494d-42e8-8772-d810bc80297f)
发现一个问题，MPv2安装下载器助手显示版本为4.0.1，但是用卸载插件的工具显示实际版本为3.5.5
![longshot20241025114619](https://github.com/user-attachments/assets/4902bdcc-1610-40bd-8624-efbacec8f2ee)

**Comment by hotlcc** [comment]
> ![image](https://private-user-images.githubusercontent.com/34505611/380004714-c044db87-494d-42e8-8772-d810bc80297f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzcwOTMsIm5iZiI6MTcyOTgzNjc5MywicGF0aCI6Ii8zNDUwNTYxMS8zODAwMDQ3MTQtYzA0NGRiODctNDk0ZC00MmU4LTg3NzItZDgxMGJjODAyOTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0Y2M0NzYxZDM5OTM1ZTk5OWZjMDkzNGY2ODIzODlmMjMzYWRjNTZkY2MyZmVkMWNiNTg3MTUxZWFjODA1ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1-tomBzJfZZfyi0c0UWnv9w7QpGdtrOXhLh6g1bsUUE) 发现一个问题，MPv2安装下载器助手显示版本为4.0.1，但是用卸载插件的工具显示实际版本为3.5.5 ![longshot20241025114619](https://private-user-images.githubusercontent.com/34505611/380004830-4902bdcc-1610-40bd-8624-efbacec8f2ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzcwOTMsIm5iZiI6MTcyOTgzNjc5MywicGF0aCI6Ii8zNDUwNTYxMS8zODAwMDQ4MzAtNDkwMmJkY2MtMTYxMC00MGJkLTg2MjQtZWZiYWNlYzhmMmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDA2MTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmYzU2OTljNDkwMjE3NDM4ODFkNjhjMTY4MDdiNmQxNmY1NGNkNTMwMzM2N2NkNDc5NGI1MWM3MTEzODhlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t4nRsf8RExu222YepAPWT-u7y3buHdRglWTK4QG5R4s)

这个是卸载插件的问题哦，v1和v2的下载器助手完全不兼容，加载就会报错。

**Comment by 7-orion** [comment]
我也活动种子显示不了 获取种子列表出错：unhashable type: 'list'
