### ISSUE TITLE
通知bug

### ISSUE THREAD

**Issue by shyblacktea** [hotlcc/MoviePilot-Plugins-Third#36]
大佬
v2版本 聚合消息通知1.7 [OneBot-11]

1.emby 无A库 plex 有A库
2.媒体库服务器通知 "新入库" 只开启emby 无开启plex
3.设定-媒体服务器-plex 未开启同步A库
4.还会通知plex的A库消息,只能关闭 设定-媒体服务器-plex 才不会通知(或者关闭  [OneBot-11] 的媒体服务器)
5.vx tg正常屏蔽A库入库消息

**Comment by hotlcc** [comment]
> 大佬 v2版本 聚合消息通知1.7 [OneBot-11]
> 
> 1.emby 无A库 plex 有A库 2.媒体库服务器通知 "新入库" 只开启emby 无开启plex 3.设定-媒体服务器-plex 未开启同步A库 4.还会通知plex的A库消息,只能关闭 设定-媒体服务器-plex 才不会通知(或者关闭 [OneBot-11] 的媒体服务器) 5.vx tg正常屏蔽A库入库消息

没太看明白你说的是什么意思

**Comment by shyblacktea** [comment]
![image](https://github.com/user-attachments/assets/04a2f297-4fd3-4c19-9e53-5d3341d7f79d)
![image](https://github.com/user-attachments/assets/5b3e06db-5e5a-4de7-b52a-5de8c6810d7d)
目录A 新入库 会被OneBot-11发送到QQ

![image](https://github.com/user-attachments/assets/f5171227-1524-4bf5-9458-ab041d8c9316)
![image](https://github.com/user-attachments/assets/f638b414-5a2a-4283-8989-98ac4c401589)

酱紫 大佬看懂了吗 0 0

**Comment by hotlcc** [comment]
聚合消息通知插件只管根据你选择的消息类型发送通知，什么入库、媒体服务什么的完全不care，跟这个插件无关。
