### ISSUE TITLE
h大佬，下载器助手的监听删种功能会影响到历史记录以外的种子。

### ISSUE THREAD

**Issue by cng10001** [hotlcc/MoviePilot-Plugins-Third#4]
**看描述，监听源文件并自动删种是针对“历史记录”中的任务的**
**但是 我在历史记录中操作一条“删除历史记录，源文件和媒体库文件”记录后，下载器中的其他种子也会受影响。**

![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/83ca0236-6a89-4ab7-801d-bb72373d72ae)
比如我再mp历史记录操作删除的是雷玛根大桥这部，但是马大帅和interstellar和马大帅这两部也被删除了（可能是因为这两部没下全，处于.!qb状态）
![342059544-7e3ad8a4-ffdc-4109-a230-a41ac5af2a7c](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/dc1484b0-ae8c-4958-9f84-2d9abba0d069)

**所以，插件能不能做到真正只限定到刚删除历史记录的那个任务呢？**

**Comment by hotlcc** [comment]
提供一下这三个种子的内容截图：
![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/14865895/67be9b61-efdf-4d63-83f2-721676b846dd)
内容存在多级的展开后截图。

**Comment by hotlcc** [comment]
再提供一下这三个种子的站点页面链接

**Comment by hotlcc** [comment]
另外，更新v3.2并重新提供上面截图2的日志

**Comment by cng10001** [comment]
![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/31fd212d-6c6c-43ae-88d7-10fe0b5d8bdd)
https://ptchdbits.co/details.php?id=355173&hit=1

![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/3b8dccaa-c02c-4fa9-89bb-01ffb7042dc2)
https://ptchdbits.co/details.php?id=32808&hit=1

![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/16a72cb2-5694-4427-966f-6e2da5a2e800)
https://kp.m-team.cc/detail/667129

**Comment by hotlcc** [comment]
> ![image](https://private-user-images.githubusercontent.com/115156545/342257167-31fd212d-6c6c-43ae-88d7-10fe0b5d8bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTc2NjMsIm5iZiI6MTcxOTIxNzM2MywicGF0aCI6Ii8xMTUxNTY1NDUvMzQyMjU3MTY3LTMxZmQyMTJkLTZjNmMtNDNhZS04OGQ3LTEwZmUwYjVkOGJkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwODIyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzZiMjYyYTcxYTkyYzBkNjFhNGRmYzk2N2ZkN2FlMDU2ZDgzYjNmYjlhOWU0OTVmMGYzMDYwNzJiYjQ0ZDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jBvIRtX8Qd8I1pHEJO9Lqs2LdE-qPHXKlKosWXkLbwQ) https://ptchdbits.co/details.php?id=355173&hit=1
> 
> ![image](https://private-user-images.githubusercontent.com/115156545/342258752-3b8dccaa-c02c-4fa9-89bb-01ffb7042dc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTc2NjMsIm5iZiI6MTcxOTIxNzM2MywicGF0aCI6Ii8xMTUxNTY1NDUvMzQyMjU4NzUyLTNiOGRjY2FhLWMwMmMtNGZhOS04OWJiLTAxZmZiNzA0MmRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwODIyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODQ1NTIzNjZiZmUzY2M3NTA4MDNjZjU0MGU5Mjg2MDBkZmFiNGJiYjBlMDEyZWM1ZTk1Yzk3YjgwNDAyNTljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ih2-nD4UI1zlNPYR8rcyoPRWXPM5rGHItEgubpPFj_Y) https://ptchdbits.co/details.php?id=32808&hit=1
> 
> ![image](https://private-user-images.githubusercontent.com/115156545/342258977-16a72cb2-5694-4427-966f-6e2da5a2e800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTc2NjMsIm5iZiI6MTcxOTIxNzM2MywicGF0aCI6Ii8xMTUxNTY1NDUvMzQyMjU4OTc3LTE2YTcyY2IyLTU2OTQtNDQyNy05NjZmLTZlMmRhNWEyZTgwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwODIyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Y2JjODAzMjZiODRjMTk2OWE3NTc5ODcwZjNhNWQ2MWQxNDgwNjQ3ZjU5Nzk0OGY5YjQxM2U4ZThiZjA4ODhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FknxTaByrUYpyoUqH0-bCR23gre-nSnq_ngHxTHoOyc) https://kp.m-team.cc/detail/667129

。。。。我没有chd站。。

**Comment by cng10001** [comment]
> 另外，更新v3.2并重新提供上面截图2的日志

我是否需要复现这个情况 然后再提供新的日志？

**Comment by hotlcc** [comment]
> > 另外，更新v3.2并重新提供上面截图2的日志
> 
> 我是否需要复现这个情况 然后再提供新的日志？

嗯，最好复现一下。

**Comment by cng10001** [comment]
好的 大佬。我稍晚些在v3.2版本下再尝试一下

**Comment by hotlcc** [comment]
还要提供qb的版本

**Comment by cng10001** [comment]
**刚试了一次这次怎么连qb里的任务都没有删** 

_插件日志_

> 【INFO】2024-06-24 20:01:01,164 - downloaderhelper - 源文件删除事件监听任务执行结束
> ValueError: too many values to unpack (expected 2)
>     ^^^^^^^^^^^^^^^^^^^
>     need_delete, reason = self.__check_need_delete_for_qbittorrent(torrent=torrent, context=context)
>   File "/app/app/plugins/downloaderhelper/__init__.py", line 1990, in __delete_single_for_qbittorrent
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     if (self.__delete_single_for_qbittorrent(qbittorrent=qbittorrent, torrent=torrent,
>   File "/app/app/plugins/downloaderhelper/__init__.py", line 1970, in __delete_batch_for_qbittorrent
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents,
>   File "/app/app/plugins/downloaderhelper/__init__.py", line 1764, in __run_for_qbittorrent
> Traceback (most recent call last):
> 【ERROR】2024-06-24 20:00:56,049 - downloaderhelper - 下载器[qBittorrent]任务执行失败: too many values to unpack (expected 2)
> 【INFO】2024-06-24 20:00:56,047 - downloaderhelper - [QB]批量自动删种开始...
> 【INFO】2024-06-24 20:00:56,045 - downloaderhelper - 子任务执行状态: 自动标签=False, 自动做种=False, 自动删种=True
> 【INFO】2024-06-24 20:00:55,969 - downloaderhelper - 下载器[qBittorrent]任务执行开始...
> 【INFO】2024-06-24 20:00:55,968 - downloaderhelper - 源文件删除事件监听任务执行开始...
> 【INFO】2024-06-24 20:00:55,926 - downloaderhelper - 监听到源文件删除事件
> 【INFO】2024-06-24 19:47:34,962 - downloaderhelper - 插件配置加载完成：{'dashboard_widget_size': None, 'dashboard_widget_refresh': None, 'dashboard_widget_display_fields': [], '_tabs': 'transmission', 'undefined': True, 'enable_notify': True, 'qb_enable_delete': True, 'qb_enable': True, 'tr_enable': True, 'listen_source_file_event': True, 'listen_download_event': False, 'tr_enable_seeding': False, 'site_name_priority': False, 'enable': True, '_config_dashboard_active_torrent_dialog_closed': False, '_config_dashboard_speed_dialog_closed': False, '_config_tracker_mappings_dialog_closed': False, 'tr_enable_delete': False, 'qb_enable_seeding': False, 'qb_enable_tagging': False}

_mp历史记录删除操作日志_

> 【INFO】2024-06-24 20:00:56,154 - command.py - 处理事件：notice.message - []
> 【INFO】2024-06-24 20:00:55,925 - command.py - 处理事件：downloadfile.deleted - [<function DownloadChain.download_file_deleted at 0x7fad13ebaf20>, <function DownloaderHelper.listen_download_file_deleted_event at 0x7fad101191c0>]
> 【WARNING】2024-06-24 20:00:55,914 - transfer.py - 文件 /videopt/qbitdownloads/刷/cmct/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv 已删除
> 【INFO】2024-06-24 20:00:55,913 - transfer.py - 开始删除文件以及空目录：/videopt/qbitdownloads/刷/cmct/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv ...
> 【WARNING】2024-06-24 20:00:55,912 - transfer.py - 目录 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023) 已删除
> 【WARNING】2024-06-24 20:00:55,812 - transfer.py - 目录 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv 已删除
> 【WARNING】2024-06-24 20:00:55,774 - transfer.py - 文件 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv 已删除
> 【INFO】2024-06-24 20:00:55,772 - transfer.py - 开始删除文件以及空目录：/videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv ...
> 

**我再试一次**

**Comment by LimLLL** [comment]
> **刚试了一次这次怎么连qb里的任务都没有删**
> 
> _插件日志_
> 
> > 【INFO】2024-06-24 20:01:01,164 - downloaderhelper - 源文件删除事件监听任务执行结束
> > ValueError: too many values to unpack (expected 2)
> > ^^^^^^^^^^^^^^^^^^^
> > need_delete, reason = self.__check_need_delete_for_qbittorrent(torrent=torrent, context=context)
> > File "/app/app/plugins/downloaderhelper/**init**.py", line 1990, in __delete_single_for_qbittorrent
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > if (self.__delete_single_for_qbittorrent(qbittorrent=qbittorrent, torrent=torrent,
> > File "/app/app/plugins/downloaderhelper/**init**.py", line 1970, in __delete_batch_for_qbittorrent
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents,
> > File "/app/app/plugins/downloaderhelper/**init**.py", line 1764, in __run_for_qbittorrent
> > Traceback (most recent call last):
> > 【ERROR】2024-06-24 20:00:56,049 - downloaderhelper - 下载器[qBittorrent]任务执行失败: too many values to unpack (expected 2)
> > 【INFO】2024-06-24 20:00:56,047 - downloaderhelper - [QB]批量自动删种开始...
> > 【INFO】2024-06-24 20:00:56,045 - downloaderhelper - 子任务执行状态: 自动标签=False, 自动做种=False, 自动删种=True
> > 【INFO】2024-06-24 20:00:55,969 - downloaderhelper - 下载器[qBittorrent]任务执行开始...
> > 【INFO】2024-06-24 20:00:55,968 - downloaderhelper - 源文件删除事件监听任务执行开始...
> > 【INFO】2024-06-24 20:00:55,926 - downloaderhelper - 监听到源文件删除事件
> > 【INFO】2024-06-24 19:47:34,962 - downloaderhelper - 插件配置加载完成：{'dashboard_widget_size': None, 'dashboard_widget_refresh': None, 'dashboard_widget_display_fields': [], '_tabs': 'transmission', 'undefined': True, 'enable_notify': True, 'qb_enable_delete': True, 'qb_enable': True, 'tr_enable': True, 'listen_source_file_event': True, 'listen_download_event': False, 'tr_enable_seeding': False, 'site_name_priority': False, 'enable': True, '_config_dashboard_active_torrent_dialog_closed': False, '_config_dashboard_speed_dialog_closed': False, '_config_tracker_mappings_dialog_closed': False, 'tr_enable_delete': False, 'qb_enable_seeding': False, 'qb_enable_tagging': False}
> 
> _mp历史记录删除操作日志_
> 
> > 【INFO】2024-06-24 20:00:56,154 - command.py - 处理事件：notice.message - []
> > 【INFO】2024-06-24 20:00:55,925 - command.py - 处理事件：downloadfile.deleted - [<function DownloadChain.download_file_deleted at 0x7fad13ebaf20>, <function DownloaderHelper.listen_download_file_deleted_event at 0x7fad101191c0>]
> > 【WARNING】2024-06-24 20:00:55,914 - transfer.py - 文件 /videopt/qbitdownloads/刷/cmct/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv 已删除
> > 【INFO】2024-06-24 20:00:55,913 - transfer.py - 开始删除文件以及空目录：/videopt/qbitdownloads/刷/cmct/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv ...
> > 【WARNING】2024-06-24 20:00:55,912 - transfer.py - 目录 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023) 已删除
> > 【WARNING】2024-06-24 20:00:55,812 - transfer.py - 目录 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv 已删除
> > 【WARNING】2024-06-24 20:00:55,774 - transfer.py - 文件 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv 已删除
> > 【INFO】2024-06-24 20:00:55,772 - transfer.py - 开始删除文件以及空目录：/videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv ...
> 
> **我再试一次**

我目前也存在和你一摸一样的报错（ValueError: too many values to unpack (expected 2）)。下载器助手是v3.3，mp是v1.9.8，qbit是v4.5.5。等待佬解决

**Comment by cng10001** [comment]
> > **刚试了一次这次怎么连qb里的任务都没有删**
> > _插件日志_
> > > 【INFO】2024-06-24 20:01:01,164 - downloaderhelper - 源文件删除事件监听任务执行结束
> > > ValueError: too many values to unpack (expected 2)
> > > ^^^^^^^^^^^^^^^^^^^
> > > need_delete, reason = self.__check_need_delete_for_qbittorrent(torrent=torrent, context=context)
> > > File "/app/app/plugins/downloaderhelper/**init**.py", line 1990, in __delete_single_for_qbittorrent
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > if (self.__delete_single_for_qbittorrent(qbittorrent=qbittorrent, torrent=torrent,
> > > File "/app/app/plugins/downloaderhelper/**init**.py", line 1970, in __delete_batch_for_qbittorrent
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > result.set_delete(self.__delete_batch_for_qbittorrent(qbittorrent=qbittorrent, torrents=torrents,
> > > File "/app/app/plugins/downloaderhelper/**init**.py", line 1764, in __run_for_qbittorrent
> > > Traceback (most recent call last):
> > > 【ERROR】2024-06-24 20:00:56,049 - downloaderhelper - 下载器[qBittorrent]任务执行失败: too many values to unpack (expected 2)
> > > 【INFO】2024-06-24 20:00:56,047 - downloaderhelper - [QB]批量自动删种开始...
> > > 【INFO】2024-06-24 20:00:56,045 - downloaderhelper - 子任务执行状态: 自动标签=False, 自动做种=False, 自动删种=True
> > > 【INFO】2024-06-24 20:00:55,969 - downloaderhelper - 下载器[qBittorrent]任务执行开始...
> > > 【INFO】2024-06-24 20:00:55,968 - downloaderhelper - 源文件删除事件监听任务执行开始...
> > > 【INFO】2024-06-24 20:00:55,926 - downloaderhelper - 监听到源文件删除事件
> > > 【INFO】2024-06-24 19:47:34,962 - downloaderhelper - 插件配置加载完成：{'dashboard_widget_size': None, 'dashboard_widget_refresh': None, 'dashboard_widget_display_fields': [], '_tabs': 'transmission', 'undefined': True, 'enable_notify': True, 'qb_enable_delete': True, 'qb_enable': True, 'tr_enable': True, 'listen_source_file_event': True, 'listen_download_event': False, 'tr_enable_seeding': False, 'site_name_priority': False, 'enable': True, '_config_dashboard_active_torrent_dialog_closed': False, '_config_dashboard_speed_dialog_closed': False, '_config_tracker_mappings_dialog_closed': False, 'tr_enable_delete': False, 'qb_enable_seeding': False, 'qb_enable_tagging': False}
> > 
> > 
> > _mp历史记录删除操作日志_
> > > 【INFO】2024-06-24 20:00:56,154 - command.py - 处理事件：notice.message - []
> > > 【INFO】2024-06-24 20:00:55,925 - command.py - 处理事件：downloadfile.deleted - [<function DownloadChain.download_file_deleted at 0x7fad13ebaf20>, <function DownloaderHelper.listen_download_file_deleted_event at 0x7fad101191c0>]
> > > 【WARNING】2024-06-24 20:00:55,914 - transfer.py - 文件 /videopt/qbitdownloads/刷/cmct/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv 已删除
> > > 【INFO】2024-06-24 20:00:55,913 - transfer.py - 开始删除文件以及空目录：/videopt/qbitdownloads/刷/cmct/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv ...
> > > 【WARNING】2024-06-24 20:00:55,912 - transfer.py - 目录 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023) 已删除
> > > 【WARNING】2024-06-24 20:00:55,812 - transfer.py - 目录 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv 已删除
> > > 【WARNING】2024-06-24 20:00:55,774 - transfer.py - 文件 /videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv 已删除
> > > 【INFO】2024-06-24 20:00:55,772 - transfer.py - 开始删除文件以及空目录：/videopt/MP媒体库/电影/冰的融化 Het smelt (2023)/1080p CMCTV▶️.mkv/[冰的融化].When.It.Melts.2024.Hami.WEB-DL.1080p.H264.AAC-CMCTV.mkv ...
> > 
> > 
> > **我再试一次**
> 
> 我目前也存在和你一摸一样的报错（ValueError: too many values to unpack (expected 2）)。下载器助手是v3.3，mp是v1.9.8，qbit是v4.5.5。等待佬解决

哦？今天更新了mp的1.9.8，下载器助手的v3.2、 难道是更新的问题？
而且下载器助手又更新到3.3了？

**Comment by hotlcc** [comment]
更新3.3.1，之前的改动产生了bug

**Comment by cng10001** [comment]
似乎其他种子不会被影响了到了，大佬是已经对这个情况作了更新吗

**Comment by hotlcc** [comment]
> 似乎其他种子不会被影响了到了，大佬是已经对这个情况作了更新吗

没有改，这块本来也没出过问题。要复现你的问题的话需要采用原先的三个种测试。

**Comment by cng10001** [comment]
@hotlcc 大佬 那个非全选标签不太会用- -。这个意思就是比如下载一个种子10集的，先下载第1集，取消选择呢其他9集，就是非全选的意思吧？
这个标签是在哪个节点会被打上呢？必须要设置执行周期还是什么？

**Comment by cng10001** [comment]
![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/e202656b-23f7-42eb-8cfa-43e6e6780974)
看到日志显示，我重新理解了下“监听源文件事件”
应该是：在mp历史记录删除源文件，能够触发本插件的自动删种功能。它并非只对该条历史记录生效，而是会对下载器中所有任务生效？
如果能做到只对在mp历史记录里删除源文件的种子生效就好了。
