### ISSUE TITLE
刷流的种子会被打上 MOVIEPILOT 和站点的标签

### ISSUE THREAD

**Issue by yfdoor** [hotlcc/MoviePilot-Plugins-Third#41]
插件设置如下：
![image](https://github.com/user-attachments/assets/daf7bab7-3950-4c15-b35a-f2f0d50ed3c1)

但是刷流的种子还是被打上了 MOVIEPILOT 和站点的标签：

> 【INFO】2024-11-27 21:19:02,680 - downloaderhelper - 下载器[QB] - 单个自动标签成功: hash = bfb121da93010e2fc78b9a8b90a5197d00c763d6, name = 神豪之我有一支神筆 2024 1080P WEB-DL H264 AAC-HDPTWeb, size = 2.98G, before = 刷流, 已整理, after = 刷流, 已整理, PT, MOVIEPILOT,明教
【INFO】2024-11-27 21:19:02,643 - downloaderhelper - 下载器[QB] - 单个自动标签成功: hash = eb5514bfdf6d0d656c78511578669671873609d7, name = 醉强王者 2024 1080P WEB-DL H264 AAC-HDPTWeb, size = 3.56G, before = 刷流, 已整理, after = 刷流, 已整理, PT, MOVIEPILOT,明教
【INFO】2024-11-27 21:19:02,611 - downloaderhelper - 下载器[QB] - 单个自动标签成功: hash = 72e5ceac15a51e74ed62b1aeb337c231799de6ec, name = 傲世狂婿 2024 1080P WEB-DL AVC1 AAC-HDPTWeb, size = 2.02G, before = MOVIEPILOT, PT, 明教, after = MOVIEPILOT, PT, MOVIEPILOT,明教
【INFO】2024-11-27 21:19:02,537 - downloaderhelper - 下载器[QB] - 单个自动标签成功: hash = fd229bfedbaf6de5928dd012b1562862eda114f3, name = 我在古代开星巴克 2024 1080P WEB-DL H264 AAC-HDPTWeb, size = 919.54M, before = 刷流, 已整理, after = 刷流, 已整理, PT, MOVIEPILOT,明教
【INFO】2024-11-27 21:19:02,489 - downloaderhelper - 下载器[QB] - 单个自动标签成功: hash = a04dbd3fdd235ebf23fb3f0d1071ea5463b59ad1, name = 賭聖3無名小子 My Name Is Nobody 2000 美亞 1080P WEB-DL AVC1 AAC-HDPTWeb, size = 1.4G, before = MOVIEPILOT, PT, 明教, after = MOVIEPILOT, PT, MOVIEPILOT,明教
【INFO】2024-11-27 21:19:02,431 - downloaderhelper - 下载器[QB] - 单个自动标签成功: hash = 5de46fa289b490ba0a875fcf5fe860eda268f368, name = 带全村脱贫后我被污蔑成白眼狼 2024 1080P WEB-DL H264 AAC-HDPTWeb, size = 1.58G, before = MOVIEPILOT, PT, 明教, after = MOVIEPILOT, PT, MOVIEPILOT,明教

**Comment by hotlcc** [comment]
排除标签只对做种和删除生效

**Comment by yfdoor** [comment]
> 排除标签只对做种和删除生效

是不是应该对“自动打标签”也要考虑排除呢：使用场景就是像上面那种含有“刷流” 标签的种子并不需要再打上 MOVIEPOLIT 的标签了，或者在具体点就是对这种“刷流” 的只打上站点标签而不打上站点前缀的 “MOVIEPLILOT”，因为只要打上 MOVIPILOT 标签后下载任务就出现在了 MP 的正在下载中，而刷流这些任务其实并不需要，请考虑一下。谢谢

**Comment by hotlcc** [comment]
> > 排除标签只对做种和删除生效
> 
> 是不是应该对“自动打标签”也要考虑排除呢：使用场景就是像上面那种含有“刷流” 标签的种子并不需要再打上 MOVIEPOLIT 的标签了，或者在具体点就是对这种“刷流” 的只打上站点标签而不打上站点前缀的 “MOVIEPLILOT”，因为只要打上 MOVIPILOT 标签后下载任务就出现在了 MP 的正在下载中，而刷流这些任务其实并不需要，请考虑一下。谢谢

【站点标签前缀】那个位置你填【MOVIPILOT,】这本身就是不规范的使用，【站点标签前缀】只是站点标签的前缀，不应该投机取巧通过这样的方式打上【MOVIPILOT】标签。而且通过MP下载的种子本身就有【MOVIPILOT】标签，通过别的方式添加的种子打上【MOVIPILOT】标签也并没有什么意义

**Comment by yfdoor** [comment]
> > > 排除标签只对做种和删除生效
> > 
> > 
> > 是不是应该对“自动打标签”也要考虑排除呢：使用场景就是像上面那种含有“刷流” 标签的种子并不需要再打上 MOVIEPOLIT 的标签了，或者在具体点就是对这种“刷流” 的只打上站点标签而不打上站点前缀的 “MOVIEPLILOT”，因为只要打上 MOVIPILOT 标签后下载任务就出现在了 MP 的正在下载中，而刷流这些任务其实并不需要，请考虑一下。谢谢
> 
> 【站点标签前缀】那个位置你填【MOVIPILOT,】这本身就是不规范的使用，【站点标签前缀】只是站点标签的前缀，不应该投机取巧通过这样的方式打上【MOVIPILOT】标签。而且通过MP下载的种子本身就有【MOVIPILOT】标签，通过别的方式添加的种子打上【MOVIPILOT】标签也并没有什么意义

好吧，可能我用的是有些偏了，我之前有时候会手动在 qb 中下载，然后希望它打上 【MOVIPILOT】标签，这样就可以在 MP 中看到了，这样可能确实违背了这个插件的设计初衷。
