### ISSUE TITLE
建议更新ptlgs的站点名称

### ISSUE THREAD

**Issue by syvshc** [hotlcc/MoviePilot-Plugins-Third#43]
PTLGS的一个tracker的网址是ptl.gs, 会被识别成ptl, 希望优化一下
![image](https://github.com/user-attachments/assets/8aeb1d3a-b08c-42a2-b2c9-8d8916f04723)

**Comment by hotlcc** [comment]
> PTLGS的一个tracker的网址是ptl.gs, 会被识别成ptl, 希望优化一下 ![image](https://private-user-images.githubusercontent.com/38098591/399148308-8aeb1d3a-b08c-42a2-b2c9-8d8916f04723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDQ1NzYsIm5iZiI6MTczNTU0NDI3NiwicGF0aCI6Ii8zODA5ODU5MS8zOTkxNDgzMDgtOGFlYjFkM2EtYjA4Yy00MmEyLWIyYzktOGQ4OTE2ZjA0NzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDA3Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MWU0YzA5NmQ2MGY5YjA2N2I0ZDY4NzY3N2JhZTQwMmQ5NzhlNWQzMGViYzkxMzNhNTk5NTkwNDYyMWZiYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rAZbd7_5i1rXWKA0YLbTSbuyKU33qpghZkDgyHG6VDs)

请使用tracker映射解决你的问题

**Comment by Slinet6056** [comment]
我设置了tracker映射，但还是不能正常识别。PTLGS的一个tracker有`:8443`的端口号，这似乎是导致问题的原因。

**Comment by hotlcc** [comment]
> 我设置了tracker映射，但还是不能正常识别。PTLGS的一个tracker有`:8443`的端口号，这似乎是导致问题的原因。

已修正
