### ISSUE TITLE
【优化建议】下载器助手界面使用优化

### ISSUE THREAD

**Issue by cng10001** [hotlcc/MoviePilot-Plugins-Third#8]
![image](https://github.com/hotlcc/MoviePilot-Plugins-Third/assets/115156545/4738dd9a-aab5-4b5a-9a6f-1d40ec5004d3)
**实测了下下载器助手的自动标签功能，不知是否能有这个2点优化
1、未全选标签增加“需开启定时执行周期”的描述。** 因为本插件有两种自动触发机制，而添加未全选标签只能是定时执行周期才能支持到，所以希望直接给个使用描述。
**2、自动标签能有更灵活的自定义选择。** 如果我只需要用到非全标签，不需要用到bt、pt和站点标签，能不能关闭呢，因为打上去也是占画面。
谢谢大佬

**Comment by hotlcc** [comment]
1、非全标签也支持事件触发；
2、“标签”是一类事物来自多个维度的不同特征属性，肯定是越全越好。细化标签开关会增加插件处理没必要的的复杂度，并且会使配置界面复杂化。而且多个标签占画面的问题也不是什么绝对的问题，仁者见仁智者见智。

**Comment by cng10001** [comment]
都可以事件触发的话那还挺好的。
看描述，事件触发是当mp添加下载任务时这个节点会触发自动标签，那如果是非全标签，添加种子的时候种子文件默认肯定是全选状态，接着比如电视剧种子选集后又是什么节点会触发非全标签呢？

**Comment by hotlcc** [comment]
> 都可以事件触发的话那还挺好的。 看描述，事件触发是当mp添加下载任务时这个节点会触发自动标签，那如果是非全标签，添加种子的时候种子文件默认肯定是全选状态，接着比如电视剧种子选集后又是什么节点会触发非全标签呢？

事件触发+定时任务补偿

**Comment by hotlcc** [comment]
> 都可以事件触发的话那还挺好的。 看描述，事件触发是当mp添加下载任务时这个节点会触发自动标签，那如果是非全标签，添加种子的时候种子文件默认肯定是全选状态，接着比如电视剧种子选集后又是什么节点会触发非全标签呢？

MP订阅的会自动选择文件，会通过事件立即触发；MP手动下载的，然后自己去下载器取消一些文件的，定时任务会定时补偿处理。
